// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJUC3eo85tOTsMd8v7AD5l5zcA8x0po8',
    appId: '1:44415498587:web:849875762d23efa43f427e',
    messagingSenderId: '44415498587',
    projectId: 'nimbus-ac6de',
    authDomain: 'nimbus-ac6de.firebaseapp.com',
    storageBucket: 'nimbus-ac6de.firebasestorage.app',
    measurementId: 'G-GSESLF9E1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkHo6jbufSkMVA6gSRHh6UjPN9-0LV-kQ',
    appId: '1:44415498587:android:99fa17c95bdca9293f427e',
    messagingSenderId: '44415498587',
    projectId: 'nimbus-ac6de',
    storageBucket: 'nimbus-ac6de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJskkaNi31_GAjgDmpo7O-RAuvDmuuTeM',
    appId: '1:44415498587:ios:020864c8aef758d43f427e',
    messagingSenderId: '44415498587',
    projectId: 'nimbus-ac6de',
    storageBucket: 'nimbus-ac6de.firebasestorage.app',
    iosBundleId: 'com.example.qent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJskkaNi31_GAjgDmpo7O-RAuvDmuuTeM',
    appId: '1:44415498587:ios:020864c8aef758d43f427e',
    messagingSenderId: '44415498587',
    projectId: 'nimbus-ac6de',
    storageBucket: 'nimbus-ac6de.firebasestorage.app',
    iosBundleId: 'com.example.qent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAJUC3eo85tOTsMd8v7AD5l5zcA8x0po8',
    appId: '1:44415498587:web:e5cc9661f0294a253f427e',
    messagingSenderId: '44415498587',
    projectId: 'nimbus-ac6de',
    authDomain: 'nimbus-ac6de.firebaseapp.com',
    storageBucket: 'nimbus-ac6de.firebasestorage.app',
    measurementId: 'G-PXB4PNH19L',
  );
}
